name: lumena_ai
description: "AI Photo Editor. Transform your photos with creative prompts in seconds."
publish_to: "none"
version: 0.3.0+27

environment:
   sdk: ^3.10.4

dependencies:
   flutter:
      sdk: flutter
   flutter_tailwind_colors: ^0.0.4
   flutter_svg: ^2.2.3
   image_picker: ^1.2.1
   http: ^1.6.0
   permission_handler: ^12.0.1
   share_plus: ^12.0.1
   image_gallery_saver_plus: ^4.0.1
   path_provider: ^2.1.5
   url_launcher: ^6.3.1
   supabase_flutter: ^2.12.0
   google_sign_in: ^7.2.0
   flutter_screenutil: ^5.9.3
   purchases_flutter: ^9.10.5
   purchases_ui_flutter: ^9.10.5
   flutter_dotenv: ^6.0.0
   crypto: ^3.0.7
   shared_preferences: ^2.3.3
   flutter_local_notifications: ^18.0.1
   timezone: ^0.10.0
   flutter_localizations:
      sdk: flutter
   intl: any
   connectivity_plus: ^6.1.2
   flutter_launcher_icons: ^0.14.4
   flutter_native_splash: ^2.4.7

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^6.0.0

flutter_native_splash:
   android: true
   ios: false
   color: "#2563eb"
   image: assets/splash_icon.png
   android_12:
      color: "#2563eb"
      image: assets/splash_icon.png

flutter_launcher_icons:
   android: true
   ios: false
   image_path: "assets/app_icon.png"
   adaptive_icon_background: "assets/app_icon_background.png"
   adaptive_icon_foreground: "assets/app_icon_foreground.png"

flutter:
   generate: true
   uses-material-design: true

   fonts:
      - family: BricolageGrotesque
        fonts:
           - asset: fonts/BricolageGrotesque-Regular.ttf
           - asset: fonts/BricolageGrotesque-Light.ttf
             weight: 300
           - asset: fonts/BricolageGrotesque-ExtraLight.ttf
             weight: 200
           - asset: fonts/BricolageGrotesque-Medium.ttf
             weight: 500
           - asset: fonts/BricolageGrotesque-SemiBold.ttf
             weight: 600
           - asset: fonts/BricolageGrotesque-Bold.ttf
             weight: 700
           - asset: fonts/BricolageGrotesque-ExtraBold.ttf
             weight: 800

   assets:
      - assets/icons/
      - assets/images/
      - .env
